version: "3"

services:
  app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app

# outra maneira eh

# rodar o nest.js apenas com node.js na maquina
# rodar o next.js apenas com node.js na maquina
# rodar o mongodb com docker